sudo: required
language: "node_js"
node_js:
  - "node"
services:
  - docker

before_install:
  - docker build -t kushsinghchb/porfolio -f Dockerfile.dev .

script:
  - docker run -e CI=true kushsinghchb/porfolio npm run test
