sudo: required
language: "node_js"
node_js:
  - "v12.18.4"
services:
  - docker

before_install:
  - docker build -t kushsinghchb/porfolio -f Dockerfile.dev .

script:
  - docker run -e CI=true kushsinghchb/porfolio npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "Portfolio"
  env: "Portfolio-env"
  bucket: "portfolio-bucket-27092020"
  bucket_path: "Portfolio"
  on:
    branch: master
